from bundlewrap.exceptions import BundleError
import re

pkg_apt = {}
files = {}
svc_systemd = {}


def add_dot(url):
    if url[-1] != '.':
        url += '.'

    return url


def add_to_list_or_create(ilist, list_key, value):
    if list_key not in ilist:
        ilist[list_key] = []

    ilist[list_key] += [value, ]


def convert_to_config_string(value):
    if isinstance(value, list):
        value = ','.join(value)
    elif isinstance(value, bool):
        value = 'yes' if value else 'no'
    elif value is None:
        value = ''

    return value


def generate_content(dns_config, default_config):
    content = [
        '# Autogenerated by bundlewrap'
    ]
    for dns_config_key, value in dns_config.items():
        default_value = default_config.get(dns_config_key, {}).get('default_value', None)
        mandatory = default_config.get(dns_config_key, {}).get('mandatory', False)
        comment = default_config.get(dns_config_key, {}).get('comment', None)

        if comment:
            content += [
                '#################################',
                '# {}'.format(default_config.get(dns_config_key, {}).get('comment', '')),
                '#',
            ]

            if not mandatory:
                content += [
                    '# {}={}'.format(dns_config_key, convert_to_config_string(default_value)),
                ]

        if default_value != value or mandatory:
            value = convert_to_config_string(value)

            content += [
                '{}={}'.format(dns_config_key, value),
            ]

        content += [
            '',  # one empty line between the configs
        ]

    content += [
        '',  # one empty line at the end of the file
    ]

    return content


svc_systemd['pdns'] = {'needs': ['pkg_apt:pdns-server', ], }


pdns_default_config = {
    '8bit-dns': {'comment': '8bit-dns	Allow 8bit dns queries', 'default_value': False},
    'allow-axfr-ips': {'comment': 'allow-axfr-ips	Allow zonetransfers only to these subnets',
                       'default_value': ['127.0.0.0/8', '::1']},
    'allow-dnsupdate-from': {
        'comment': 'allow-dnsupdate-from	A global setting to allow DNS updates from these IP ranges.',
        'default_value': ['127.0.0.0/8', '::1']},
    'allow-notify-from': {
        'comment': 'allow-notify-from	Allow AXFR NOTIFY from these IP ranges. If empty, drop all incoming notifies.',
        'default_value': ['0.0.0.0/0', '::/0']},
    # 'allow-recursion': {'comment': 'allow-recursion	List of subnets that are allowed to recurse',
    #                     'default_value': ['0.0.0.0/0']},
    'allow-unsigned-notify': {
        'comment': 'allow-unsigned-notify	Allow unsigned notifications for TSIG secured domains',
        'default_value': True},
    'allow-unsigned-supermaster': {
        'comment': 'allow-unsigned-supermaster	Allow supermasters to create zones without TSIG signed NOTIFY',
        'default_value': True},
    'also-notify': {'comment': 'also-notify	When notifying a domain, also notify these nameservers',
                    'default_value': ''},
    'any-to-tcp': {'comment': 'any-to-tcp	Answer ANY queries with tc=1, shunting to TCP', 'default_value': True},
    'api': {'comment': 'api	Enable/disable the REST API (including HTTP listener)', 'default_value': False},
    'api-key': {'comment': 'api-key	Static pre-shared authentication key for access to the REST API',
                'default_value': ''},
    # 'api-logfile': {'comment': 'api-logfile	Location of the server logfile (used by the REST API)',
    #                 'default_value': '/var/log/pdns.log'},
    # 'api-readonly': {'comment': 'api-readonly	Disallow data modification through the REST API when set',
    #                  'default_value': False},
    'axfr-fetch-timeout': {'comment': 'axfr-fetch-timeout	Maximum time in seconds for inbound AXFR to start or '
                                      'be idle after starting',
                           'default_value': 10},
    'axfr-lower-serial': {'comment': 'axfr-lower-serial	Also AXFR a zone from a master with a lower serial',
                          'default_value': False},
    'cache-ttl': {'comment': 'cache-ttl	Seconds to store packets in the PacketCache', 'default_value': 20},
    'carbon-instance': {'comment': 'carbon-instance	If set overwrites the the instance name default', 'default_value': 'auth'},
    'carbon-interval': {'comment': 'carbon-interval	Number of seconds between carbon (graphite) updates',
                        'default_value': 30},
    'carbon-namespace': {'comment': 'carbon-namespace	If set overwrites the first part of the carbon string', 'default_value': 'pdns'},
    'carbon-ourname': {'comment': 'carbon-ourname	If set, overrides our reported hostname for carbon stats',
                       'default_value': ''},
    'carbon-server': {
        'comment': 'carbon-server	If set, send metrics in carbon (graphite) format to this server IP address',
        'default_value': ''},
    'chroot': {'comment': 'chroot	If set, chroot to this directory for more security', 'default_value': ''},
    'config-dir': {'comment': 'config-dir	Location of configuration directory (pdns.conf)',
                   'default_value': '/etc/powerdns'},
    'config-name': {'comment': 'config-name	Name of this virtual configuration - will rename the binary image',
                    'default_value': ''},
    'consistent-backends': {'comment': 'consistent-backends	Assume individual domains are not divided over backends. Send only ANY lookup operations to the backend to reduce the number of lookups', 'default_value': False},
    'control-console': {'comment': 'control-console	Debugging switch - don\'t use', 'default_value': False},
    'daemon': {'comment': 'daemon	Operate as a daemon', 'default_value': False},
    'default-api-rectify': {'comment': 'default-api-rectify	Default API-RECTIFY value for zones', 'default_value': True},
    'default-ksk-algorithm': {'comment': 'default-ksk-algorithm	Default KSK algorithm', 'default_value': 'ecdsa256'},
    'default-ksk-size': {'comment': 'default-ksk-size	Default KSK size (0 means default)', 'default_value': 0},
    'default-publish-cdnskey': {'comment': 'default-publish-cdnskey	Default value for PUBLISH-CDNSKEY', 'default_value': ''},
    'default-publish-cds': {'comment': 'default-publish-cds	Default value for PUBLISH-CDS', 'default_value': ''},
    'default-soa-content': {'comment': 'default-soa-content	Default SOA content', 'default_value': 'a.misconfigured.dns.server.invalid hostmaster.@ 0 10800 3600 604800 3600'},
    'default-soa-edit': {'comment': 'default-soa-edit	Default SOA-EDIT value', 'default_value': ''},
    'default-soa-edit-signed': {'comment': 'default-soa-edit-signed	Default SOA-EDIT value for signed zones',
                                'default_value': ''},
    # 'default-soa-mail': {
    #     'comment': 'default-soa-mail	mail address to insert in the SOA record if none set in the backend',
    #     'default_value': ''},
    # 'default-soa-name': {'comment': 'default-soa-name	name to insert in the SOA record if none set in the backend',
    #                      'default_value': 'a.misconfigured.powerdns.server'},
    'default-ttl': {'comment': 'default-ttl	Seconds a result is valid if not set otherwise', 'default_value': 3600},
    'default-zsk-algorithm': {'comment': 'default-zsk-algorithm	Default ZSK algorithm', 'default_value': ''},
    'default-zsk-size': {'comment': 'default-zsk-size	Default ZSK size (0 means default)', 'default_value': 0},
    'direct-dnskey': {'comment': 'direct-dnskey	Fetch DNSKEY, CDS and CDNSKEY RRs from backend during DNSKEY or CDS/CDNSKEY synthesis',
                      'default_value': False},
    'disable-axfr': {'comment': 'disable-axfr	Disable zonetransfers but do allow TCP queries',
                     'default_value': False},
    'disable-axfr-rectify': {
        'comment': 'disable-axfr-rectify	'
                   'Disable the rectify step during an outgoing AXFR. Only required for regression testing.',
        'default_value': False},
    'disable-syslog': {
        'comment': 'disable-syslog	Disable logging to syslog, useful when running inside a supervisor that logs stdout',
        'default_value': False},
    # 'disable-tcp': {'comment': 'disable-tcp	Do not listen to TCP queries', 'default_value': False},
    'distributor-threads': {
        'comment': 'distributor-threads	Default number of Distributor (backend) threads to start',
        'default_value': 3},
    'dname-processing': {'comment': 'dname-processing	If we should support DNAME records', 'default_value': False},
    'dnssec-key-cache-ttl': {'comment': 'dnssec-key-cache-ttl	Seconds to cache DNSSEC keys from the database',
                             'default_value': 30},
    'dnsupdate': {'comment': 'dnsupdate	Enable/Disable DNS update (RFC2136) support. Default is no.',
                  'default_value': False},
    # 'do-ipv6-additional-processing': {'comment': 'do-ipv6-additional-processing	Do AAAA additional processing',
    #                                   'default_value': True},
    'domain-metadata-cache-ttl': {
        'comment': 'domain-metadata-cache-ttl	Seconds to cache domain metadata from the database',
        'default_value': 60},
    'edns-subnet-processing': {'comment': 'edns-subnet-processing	If we should act on EDNS Subnet options',
                               'default_value': False},
    'enable-lua-records': {'comment': 'enable-lua-records	Process LUA records for all zones (metadata overrides this)', 'default_value': False},
    'entropy-source': {'comment': 'entropy-source	If set, read entropy from this file',
                       'default_value': '/dev/urandom'},
    'expand-alias': {'comment': 'expand-alias	Expand ALIAS records', 'default_value': False},
    # 'experimental-lua-policy-script': {'comment': 'experimental-lua-policy-script	Lua script for the policy engine',
    #                                    'default_value': ''},
    'forward-dnsupdate': {
        'comment': 'forward-dnsupdate	'
                   'A global setting to allow DNS update packages that are for a Slave domain, '
                   'to be forwarded to the master.',
        'default_value': True},
    'forward-notify': {
        'comment': 'forward-notify	'
                   'IP addresses to forward received notifications to regardless of master or slave settings',
        'default_value': ''},
    'guardian': {'comment': 'guardian	Run within a guardian process', 'default_value': False},
    'include-dir': {'comment': 'include-dir	Include *.conf files from this directory', 'default_value': ''},
    'launch': {'comment': 'launch	Which backends to launch and order to query them in', 'default_value': None},
    'load-modules': {'comment': 'load-modules	Load this module - supply absolute or relative path',
                     'default_value': ''},
    'local-address': {'comment': 'local-address	Local IP addresses to which we bind', 'default_value': ['0.0.0.0', '::']},
    'local-address-nonexist-fail': {
        'comment': 'local-address-nonexist-fail	Fail to start if one or more of '
                   'the local-address\'s do not exist on this server',
        'default_value': True},
    'local-ipv6': {'comment': 'local-ipv6	DEPRECATED, will be removed, move your IPs to local-address', 'default_value': '::'},
    # 'local-ipv6-nonexist-fail': {
    #     'comment': 'local-ipv6-nonexist-fail	Fail to start if one or more of '
    #                'the local-ipv6 addresses do not exist on this server',
    #     'default_value': True},
    'local-port': {'comment': 'local-port	The port on which we listen', 'default_value': 53},
    'log-dns-details': {'comment': 'log-dns-details	If PDNS should log DNS non-erroneous details',
                        'default_value': False},
    'log-dns-queries': {'comment': 'log-dns-queries	If PDNS should log all incoming DNS queries',
                        'default_value': False},
    'log-timestamp': {'comment': 'log-timestamp	Print timestamps in log lines', 'default_value': True},
    'logging-facility': {'comment': 'logging-facility	Log under a specific facility', 'default_value': ''},
    'loglevel': {'comment': 'loglevel	Amount of logging. Higher is more. Do not set below 3', 'default_value': 4},
    'lua-axfr-script': {'comment': 'lua-axfr-script	Script to be used to edit incoming AXFRs', 'default_value': ''},
    'lua-dnsupdate-policy-script': {
        'comment': 'lua-dnsupdate-policy-script	Lua script with DNS update policy handler', 'default_value': ''},
    'lua-health-checks-expire-delay': {'comment': 'lua-health-checks-expire-delay	Stops doing health checks after the record hasn\'t been used for that delay (in seconds)', 'default_value': 3600},
    'lua-health-checks-interval': {'comment': 'lua-health-checks-interval	LUA records health checks monitoring interval in seconds', 'default_value': 5},
    'lua-prequery-script': {'comment': 'lua-prequery-script	Lua script with prequery handler (DO NOT USE)',
                            'default_value': ''},
    'lua-records-exec-limit': {'comment': 'lua-records-exec-limit	LUA records scripts execution limit (instructions count). Values <= 0 mean no limit', 'default_value': 1000},
    'master': {'comment': 'master	Act as a master', 'default_value': False},
    'max-cache-entries': {'comment': 'max-cache-entries	Maximum number of entries in the query cache',
                          'default_value': 1000000},
    'max-ent-entries': {'comment': 'max-ent-entries	Maximum number of empty non-terminals in a zone',
                        'default_value': 100000},
    'max-generate-steps': {'comment': 'max-generate-steps	Maximum number of $GENERATE steps when loading a zone from a file', 'default_value': 0},
    'max-nsec3-iterations': {'comment': 'max-nsec3-iterations	Limit the number of NSEC3 hash iterations',
                             'default_value': 500},
    'max-packet-cache-entries': {'comment': 'max-packet-cache-entries	Maximum number of entries in the packet cache',
                                 'default_value': 1000000},
    'max-queue-length': {'comment': 'max-queue-length	Maximum queuelength before considering situation lost',
                         'default_value': 5000},
    'max-signature-cache-entries': {
        'comment': 'max-signature-cache-entries	Maximum number of signatures cache entries', 'default_value': ''},
    'max-tcp-connection-duration': {
        'comment': 'max-tcp-connection-duration	Maximum time in seconds that a '
                   'TCP DNS connection is allowed to stay open.',
        'default_value': 0},
    'max-tcp-connections': {'comment': 'max-tcp-connections	Maximum number of TCP connections', 'default_value': 20},
    'max-tcp-connections-per-client': {
        'comment': 'max-tcp-connections-per-client	Maximum number of simultaneous TCP connections per client',
        'default_value': 0},
    'max-tcp-transactions-per-conn': {
        'comment': 'max-tcp-transactions-per-conn	Maximum number of subsequent queries per TCP connection',
        'default_value': 0},
    'module-dir': {'comment': 'module-dir	Default directory for modules', 'default_value': '/usr/lib/powerdns'},
    'negquery-cache-ttl': {'comment': 'negquery-cache-ttl	Seconds to store negative query results in the QueryCache',
                           'default_value': 60},
    'no-shuffle': {'comment': 'no-shuffle	Set this to prevent random shuffling of answers - for regression testing',
                   'default_value': 'off'},
    'non-local-bind': {
        'comment': 'non-local-bind	Enable binding to non-local addresses by using FREEBIND / BINDANY socket options',
        'default_value': False},
    'only-notify': {'comment': 'only-notify	Only send AXFR NOTIFY to these IP addresses or netmasks',
                    'default_value': ['0.0.0.0/0', '::/0']},
    # 'out-of-zone-additional-processing': {
    #     'comment': 'out-of-zone-additional-processing	Do out of zone additional processing', 'default_value': True},
    'outgoing-axfr-expand-alias': {'comment': 'outgoing-axfr-expand-alias	Expand ALIAS records during outgoing AXFR',
                                   'default_value': False},
    'overload-queue-length': {'comment': 'overload-queue-length	Maximum queuelength moving to packetcache only',
                              'default_value': 0},
    'prevent-self-notification': {
        'comment': 'prevent-self-notification	Don\'t send notifications to what we think is ourself',
        'default_value': True},
    'query-cache-ttl': {'comment': 'query-cache-ttl	Seconds to store query results in the QueryCache',
                        'default_value': 20},
    'query-local-address': {'comment': 'query-local-address	Source IP addresses for sending queries',
                            'default_value': '0.0.0.0 ::'},
    'query-local-address6': {'comment': 'query-local-address6	DEPRECATED: Use query-local-address. Source IPv6 '
                                        'address for sending queries',
                             'default_value': ''},
    'query-logging': {'comment': 'query-logging	Hint backends that queries should be logged',
                      'default_value': False},
    'queue-limit': {'comment': 'queue-limit	Maximum number of milliseconds to queue a query', 'default_value': 1500},
    'receiver-threads': {'comment': 'receiver-threads	Default number of receiver threads to start',
                         'default_value': 1},
    # 'recursive-cache-ttl': {'comment': 'recursive-cache-ttl	'
    #                                    'Seconds to store packets for recursive queries in the PacketCache',
    #                                    'default_value': 10},
    # 'recursor': {'comment': 'recursor	If recursion is desired, IP address of a recursing nameserver',
    #              'default_value': False},
    'resolver': {'comment': 'resolver	Use this resolver for ALIAS and the internal stub resolver',
                 'default_value': False},
    'retrieval-threads': {'comment': 'retrieval-threads	Number of AXFR-retrieval threads for slave operation',
                          'default_value': 2},
    'reuseport': {
        'comment': 'reuseport	Enable higher performance on compliant kernels by using SO_REUSEPORT '
                   'allowing each receiver thread to open its own socket',
        'default_value': False},
    'rng': {'comment': 'rng	Specify the random number generator to use. Valid values are auto,sodium,openssl,'
                       'getrandom,arc4random,urandom.', 'default_value': 'auto'},
    'security-poll-suffix': {
        'comment': 'security-poll-suffix	Domain name from which to query security update notifications',
        'default_value': 'secpoll.powerdns.com.'},
    'send-signed-notify': {'comment': 'send-signed-notify	Send TSIG secured NOTIFY if TSIG key is configured for '
                                      'a domain',
                           'default_value': True},
    'server-id': {
        'comment': 'server-id	Returned when queried for \'id.server\' TXT or NSID, defaults to hostname '
                   '- disabled or custom',
        'default_value': ''},
    'setgid': {'comment': 'setgid	If set, change group id to this gid for more security', 'default_value': ''},
    'setuid': {'comment': 'setuid	If set, change user id to this uid for more security', 'default_value': ''},
    'signing-threads': {'comment': 'signing-threads	Default number of signer threads to start', 'default_value': 3},
    'slave': {'comment': 'slave	Act as a slave', 'default_value': False},
    'slave-cycle-interval': {'comment': 'slave-cycle-interval	Schedule slave freshness checks once every .. seconds',
                             'default_value': 60},
    'slave-renotify': {'comment': 'slave-renotify	If we should send out notifications for slaved updates',
                       'default_value': False},
    # 'soa-expire-default': {'comment': 'soa-expire-default	Default SOA expire', 'default_value': 604800},
    # 'soa-minimum-ttl': {'comment': 'soa-minimum-ttl	Default SOA minimum ttl', 'default_value': 3600},
    # 'soa-refresh-default': {'comment': 'soa-refresh-default	Default SOA refresh', 'default_value': 10800},
    # 'soa-retry-default': {'comment': 'soa-retry-default	Default SOA retry', 'default_value': 3600},
    'socket-dir': {'comment': 'socket-dir	Where the controlsocket will live, /var/run/pdns when unset and not '
                              'chrooted. Set to the RUNTIME_DIRECTORY environment variable when that variable has '
                              'a value (e.g. under systemd).',
                   'default_value': ''},
    'superslave': {'comment': 'superslave	Act as a superslave', 'default_value': False},
    'tcp-control-address': {
        'comment': 'tcp-control-address	If set, PowerDNS can be controlled over TCP on this address',
        'default_value': ''},
    'tcp-control-port': {'comment': 'tcp-control-port	If set, PowerDNS can be controlled over TCP on this address',
                         'default_value': 53000},
    'tcp-control-range': {
        'comment': 'tcp-control-range	If set, remote control of PowerDNS is possible over these networks only',
        'default_value': ['127.0.0.0/8', '10.0.0.0/8', '192.168.0.0/16', '172.16.0.0/12', '::1/128', 'fe80::/10']},
    'tcp-control-secret': {
        'comment': 'tcp-control-secret	If set, PowerDNS can be controlled over TCP after passing this secret',
        'default_value': ''},
    'tcp-fast-open': {
        'comment': 'tcp-fast-open	Enable TCP Fast Open support on the listening sockets, using the supplied '
                   'numerical value as the queue size',
        'default_value': 0},
    'tcp-idle-timeout': {
        'comment': 'tcp-idle-timeout	Maximum time in seconds that a TCP DNS connection is allowed to stay '
                   'open while being idle',
        'default_value': 5},
    'traceback-handler': {'comment': 'traceback-handler	Enable the traceback handler (Linux only)',
                          'default_value': True},
    'trusted-notification-proxy': {'comment': 'trusted-notification-proxy	IP address of incoming notification proxy',
                                   'default_value': ''},
    'udp-truncation-threshold': {'comment': 'udp-truncation-threshold	Maximum UDP response size before we truncate',
                                 'default_value': 1232},
    'upgrade-unknown-types': {'comment': 'upgrade-unknown-types	Transparently upgrade known TYPExxx records. '
                                         'Recommended to keep off, except for PowerDNS upgrades until data sources '
                                         'are cleaned up', 'default_value': False},
    'version-string': {'comment': 'version-string	PowerDNS version in packets - full, anonymous, powerdns or custom',
                       'default_value': 'full'},
    'webserver': {'comment': 'webserver	Start a webserver for monitoring (api=yes also enables the HTTP listener)',
                  'default_value': False},
    'webserver-address': {'comment': 'webserver-address	IP Address of webserver/API to listen on',
                          'default_value': '127.0.0.1'},
    'webserver-allow-from': {
        'comment': 'webserver-allow-from	Webserver/API access is only allowed from these subnets',
        'default_value': ['127.0.0.1', '::1']},
    'webserver-loglevel': {'comment': 'webserver-loglevel	Amount of logging in the webserver (none, normal, detailed)',
                           'default_value': 'normal'},
    'webserver-max-bodysize': {'comment': 'webserver-max-bodysize	Webserver/API maximum request/response '
                                          'body size in megabytes',
                               'default_value': 2},
    'webserver-password': {'comment': 'webserver-password	Password required for accessing the webserver',
                           'default_value': ''},
    'webserver-port': {'comment': 'webserver-port	Port of webserver/API to listen on', 'default_value': 8081},
    'webserver-print-arguments': {'comment': 'webserver-print-arguments	If the webserver should print arguments',
                                  'default_value': False},
    'write-pid': {'comment': 'write-pid	Write a PID file', 'default_value': True},
    'xfr-max-received-mbytes': {
        'comment': 'xfr-max-received-mbytes	Maximum number of megabytes received from an incoming XFR',
        'default_value': 100},
}


pdns_recursor_default_config = {
    'allow-from': {'comment': 'allow-from	If set, only allow these comma separated netmasks to recurse',
                   'default_value': '127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, '
                                    '172.16.0.0/12, ::1/128, fc00::/7, fe80::/10', },
    'allow-from-file': {'comment': 'allow-from-file	If set, load allowed netmasks from this file',
                        'default_value': '', },
    'allow-trust-anchor-query': {'comment': 'allow-trust-anchor-query	Allow queries for trustanchor.server CH TXT and negativetrustanchor.server CH TXT', 'default_value': False},

    'any-to-tcp': {'comment': 'any-to-tcp	Answer ANY queries with tc=1, shunting to TCP', 'default_value': False, },
    'api-config-dir': {'comment': 'api-config-dir	Directory where REST API stores config and zones',
                       'default_value': '', },
    'api-key': {'comment': 'api-key	Static pre-shared authentication key for access to the REST API',
                'default_value': '', },
    # 'api-logfile': {'comment': 'api-logfile	Location of the server logfile (used by the REST API)',
    #                 'default_value': '/var/log/pdns.log', },
    # 'api-readonly': {'comment': 'api-readonly	Disallow data modification through the REST API when set',
    #                  'default_value': False, },
    'auth-zones': {
        'comment': 'auth-zones	Zones for which we have authoritative data, comma separated domain=file pairs ',
        'default_value': '', },
    'carbon-instance': {'comment': 'carbon-instance	If set overwrites the the instance name default', 'default_value': 'recursor'},

    'carbon-interval': {'comment': 'carbon-interval	Number of seconds between carbon (graphite) updates',
                        'default_value': 30, },
    'carbon-namespace': {'comment': 'carbon-namespace	If set overwrites the first part of the carbon string', 'default_value': 'pdns'},
    'carbon-ourname': {'comment': 'carbon-ourname	If set, overrides our reported hostname for carbon stats',
                       'default_value': '', },
    'carbon-server': {
        'comment': 'carbon-server	If set, send metrics in carbon (graphite) format to this server IP address',
        'default_value': '', },
    'chroot': {'comment': 'chroot	switch to chroot jail', 'default_value': '', },
    'client-tcp-timeout': {'comment': 'client-tcp-timeout	Timeout in seconds when talking to TCP clients',
                           'default_value': 2, },
    'config-dir': {'comment': 'config-dir	Location of configuration directory (recursor.conf)',
                   'default_value': None, 'mandatory': True, },
    'config-name': {'comment': 'config-name	Name of this virtual configuration - will rename the binary image',
                    'default_value': '', },
    'cpu-map': {'comment': 'cpu-map	Thread to CPU mapping, space separated thread-id=cpu1,cpu2..cpuN pairs',
                'default_value': '', },
    'daemon': {'comment': 'daemon	Operate as a daemon', 'default_value': False, },
    'delegation-only': {'comment': 'delegation-only	Which domains we only accept delegations from',
                        'default_value': '', },
    'disable-packetcache': {'comment': 'disable-packetcache	Disable packetcache', 'default_value': False, },
    'disable-syslog': {
        'comment': 'disable-syslog	Disable logging to syslog, useful when running inside a supervisor that logs stdout',
        'default_value': False, },
    'distribution-load-factor': {'comment': 'distribution-load-factor	The load factor used when PowerDNS is distributing queries to worker threads', 'default_value': 0.0},
    'distribution-pipe-buffer-size': {'comment': 'distribution-pipe-buffer-size	Size in bytes of the internal buffer of the pipe used by the distributor to pass incoming queries to a worker thread', 'default_value': 0},
    'distributor-threads': {'comment': 'distributor-threads	Launch this number of distributor threads, distributing queries to other threads', 'default_value': 0},
    'dns64-prefix': {'comment': 'dns64-prefix	DNS64 prefix', 'default_value': ''},

    'dnssec': {'comment': 'dnssec	DNSSEC mode: off/process-no-validate (default)/process/log-fail/validate',
               'default_value': 'process-no-validate', },
    'dnssec-log-bogus': {'comment': 'dnssec-log-bogus	Log DNSSEC bogus validations', 'default_value': False, },
    'dont-query': {'comment': 'dont-query	If set, do not query these netmasks for DNS data',
                   'default_value': '127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, '
                                    '172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, '
                                    '192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, '
                                    '::ffff:0:0/96, 100::/64, 2001:db8::/32', },
    'dont-throttle-names': {'comment': 'dont-throttle-names	Do not throttle nameservers with this name or suffix', 'default_value': ''},
    'dont-throttle-netmasks': {'comment': 'dont-throttle-netmasks	Do not throttle nameservers with this IP netmask', 'default_value': ''},
    'ecs-add-for': {'comment': 'ecs-add-for	List of client netmasks for which EDNS Client Subnet will be added', 'default_value': ['0.0.0.0/0', '::/0', '!127.0.0.0/8', '!10.0.0.0/8', '!100.64.0.0/10', '!169.254.0.0/16', '!192.168.0.0/16', '!172.16.0.0/12', '!::1/128', '!fc00::/7', '!fe80::/10']},
    'ecs-cache-limit-ttl': {'comment': 'ecs-cache-limit-ttl	Minimum TTL to cache ECS response', 'default_value': 0},

    'ecs-ipv4-bits': {'comment': 'ecs-ipv4-bits	Number of bits of IPv4 address to pass for EDNS Client Subnet',
                      'default_value': 24, },
    'ecs-ipv4-cache-bits': {'comment': 'ecs-ipv4-cache-bits	Maximum number of bits of IPv4 mask to cache ECS response', 'default_value': 24},

    'ecs-ipv6-bits': {'comment': 'ecs-ipv6-bits	Number of bits of IPv6 address to pass for EDNS Client Subnet',
                      'default_value': 56, },
    'ecs-ipv6-cache-bits': {'comment': 'ecs-ipv6-cache-bits	Maximum number of bits of IPv6 mask to cache ECS response', 'default_value': 56},
    'ecs-minimum-ttl-override': {'comment': 'ecs-minimum-ttl-override	Set under adverse conditions, a minimum TTL for records in ECS-specific answers', 'default_value': 0},

    'ecs-scope-zero-address': {
        'comment': 'ecs-scope-zero-address	Address to send to whitelisted authoritative servers for '
                   'incoming queries with ECS prefix-length source of 0',
        'default_value': '', },
    'edns-outgoing-bufsize': {'comment': 'edns-outgoing-bufsize	Outgoing EDNS buffer size',
                              'default_value': 1232, },
    'edns-subnet-whitelist': {
        'comment': 'edns-subnet-whitelist	List of netmasks and domains that we should enable EDNS subnet for',
        'default_value': '', },
    'entropy-source': {'comment': 'entropy-source	If set, read entropy from this file',
                       'default_value': '/dev/urandom', },
    'etc-hosts-file': {'comment': 'etc-hosts-file	Path to \'hosts\' file', 'default_value': '/etc/hosts', },
    'export-etc-hosts': {'comment': 'export-etc-hosts	If we should serve up contents from /etc/hosts',
                         'default_value': 'off', },
    'export-etc-hosts-search-suffix': {
        'comment': 'export-etc-hosts-search-suffix	Also serve up the contents of /etc/hosts with this suffix',
        'default_value': '', },
    'forward-zones': {'comment': 'forward-zones	Zones for which we forward queries, comma separated domain=ip pairs',
                      'default_value': '', },
    'forward-zones-file': {'comment': 'forward-zones-file	File with (+)domain=ip pairs for forwarding',
                           'default_value': '', },
    'forward-zones-recurse': {
        'comment': 'forward-zones-recurse	Zones for which we forward queries with recursion bit, '
                   'comma separated domain=ip pairs',
        'default_value': '', },
    'gettag-needs-edns-options': {
        'comment': 'gettag-needs-edns-options	If EDNS Options should be extracted before calling the gettag() hook',
        'default_value': False, },
    'hint-file': {'comment': 'hint-file	If set, load root hints from this file', 'default_value': '', },
    'include-dir': {'comment': 'include-dir	Include *.conf files from this directory', 'default_value': '', },
    'latency-statistic-size': {
        'comment': 'latency-statistic-size	Number of latency values to calculate the qa-latency average',
        'default_value': 10000, },
    'local-address': {
        'comment': 'local-address	IP addresses to listen on, separated by spaces or commas. Also accepts ports.',
        'default_value': None, 'mandatory': True, },
    'local-port': {'comment': 'local-port	port to listen on', 'default_value': 53, },
    'log-common-errors': {'comment': 'log-common-errors	If we should log rather common errors',
                          'default_value': False, },
    'log-rpz-changes': {'comment': 'log-rpz-changes	Log additions and removals to RPZ zones at Info level',
                        'default_value': False, },
    'log-timestamp': {
        'comment': 'log-timestamp	Print timestamps in log lines, useful to disable when running with a '
                   'tool that timestamps stdout already',
        'default_value': True, },
    'logging-facility': {'comment': 'logging-facility	Facility to log messages as. 0 corresponds to local0',
                         'default_value': '', },
    'loglevel': {'comment': 'loglevel	Amount of logging. Higher is more. Do not set below 3',
                 'default_value': 6, },
    'lowercase-outgoing': {'comment': 'lowercase-outgoing	Force outgoing questions to lowercase',
                           'default_value': False, },
    'lua-config-file': {'comment': 'lua-config-file	More powerful configuration options', 'default_value': None,
                        'mandatory': True, },
    'lua-dns-script': {
        'comment': 'lua-dns-script	Filename containing an optional \'lua\' script that will be '
                   'used to modify dns answers',
        'default_value': '', },
    'lua-maintenance-interval': {'comment': 'lua-maintenance-interval	Number of seconds between calls to the lua user defined maintenance() function', 'default_value': 1},
    'max-cache-bogus-ttl': {'comment': 'max-cache-bogus-ttl	maximum number of seconds to keep a Bogus (positive or negative) cached entry in memory', 'default_value': 3600},
    'max-cache-entries': {'comment': 'max-cache-entries	If set, maximum number of entries in the main cache',
                          'default_value': 1000000, },
    'max-cache-ttl': {'comment': 'max-cache-ttl	maximum number of seconds to keep a cached entry in memory',
                      'default_value': 86400, },
    'max-concurrent-requests-per-tcp-connection': {'comment': 'max-concurrent-requests-per-tcp-connection	Maximum number of requests handled concurrently per TCP connection', 'default_value': 10},
    'max-generate-steps': {'comment': 'max-generate-steps	Maximum number of $GENERATE steps when loading a zone from a file', 'default_value': 0},

    'max-mthreads': {'comment': 'max-mthreads	Maximum number of simultaneous Mtasker threads',
                     'default_value': 2048, },
    'max-negative-ttl': {
        'comment': 'max-negative-ttl	maximum number of seconds to keep a negative cached entry in memory',
        'default_value': 3600, },
    'max-ns-address-qperq': {'comment': 'max-ns-address-qperq	Maximum outgoing NS address queries per query',
                             'default_value': 10, },
    'max-packetcache-entries': {
        'comment': 'max-packetcache-entries	maximum number of entries to keep in the packetcache',
        'default_value': 500000, },
    'max-qperq': {'comment': 'max-qperq	Maximum outgoing queries per query', 'default_value': 60, },
    'max-recursion-depth': {
        'comment': 'max-recursion-depth	Maximum number of internal recursion calls per query, 0 for unlimited',
        'default_value': 40, },
    'max-tcp-clients': {'comment': 'max-tcp-clients	Maximum number of simultaneous TCP clients',
                        'default_value': 128, },
    'max-tcp-per-client': {
        'comment': 'max-tcp-per-client	If set, maximum number of TCP sessions per client (IP address)',
        'default_value': '0', },
    'max-tcp-queries-per-connection': {
        'comment': 'max-tcp-queries-per-connection	If set, maximum number of TCP queries in a TCP connection',
        'default_value': '0', },
    'max-total-msec': {
        'comment': 'max-total-msec	Maximum total wall-clock time per query in milliseconds, 0 for unlimited',
        'default_value': 7000, },
    'max-udp-queries-per-round': {
        'comment': 'max-udp-queries-per-round	Maximum number of UDP queries processed per recvmsg() round, '
                   'before returning back to normal processing',
        'default_value': 10000, },
    'minimum-ttl-override': {'comment': 'minimum-ttl-override	Set under adverse conditions, a minimum TTL',
                             'default_value': '0', },
    'network-timeout': {'comment': 'network-timeout	Wait this number of milliseconds for network i/o',
                        'default_value': 1500, },
    'no-shuffle': {'comment': 'no-shuffle	Don\'t change', 'default_value': 'off', },
    'non-local-bind': {
        'comment': 'non-local-bind	Enable binding to non-local addresses by using FREEBIND / BINDANY socket options',
        'default_value': False, },
'nothing-below-nxdomain': {'comment': 'nothing-below-nxdomain	When an NXDOMAIN exists in cache for a name with fewer labels than the qname, send NXDOMAIN without doing a lookup (see RFC 8020)', 'default_value': 'dnssec'},

    'nsec3-max-iterations': {
        'comment': 'nsec3-max-iterations	Maximum number of iterations allowed for an NSEC3 record',
        'default_value': 2500, },
    'packetcache-servfail-ttl': {
        'comment': 'packetcache-servfail-ttl	maximum number of seconds to keep a cached servfail entry in packetcache',
        'default_value': 60, },
    'packetcache-ttl': {'comment': 'packetcache-ttl	maximum number of seconds to keep a cached entry in packetcache',
                        'default_value': 3600, },
    'pdns-distributes-queries': {
        'comment': 'pdns-distributes-queries	If PowerDNS itself should distribute queries over threads',
        'default_value': True, },
    'processes': {'comment': 'processes	Launch this number of processes (EXPERIMENTAL, DO NOT CHANGE)',
                  'default_value': 1, },
    'protobuf-use-kernel-timestamp': {'comment': 'protobuf-use-kernel-timestamp	Compute the latency of queries in protobuf messages by using the timestamp set by the kernel when the query was received (when available)', 'default_value': ''},
    'proxy-protocol-from': {'comment': 'proxy-protocol-from	A Proxy Protocol header is only allowed from these subnets', 'default_value': ''},
    'proxy-protocol-maximum-size': {'comment': 'proxy-protocol-maximum-size	The maximum size of a proxy protocol payload, including the TLV values', 'default_value': 512},
    'public-suffix-list-file': {'comment': 'public-suffix-list-file	Path to the Public Suffix List file, if any', 'default_value': ''},
    'qname-minimization': {'comment': 'qname-minimization	Use Query Name Minimization', 'default_value': True},

    'query-local-address': {'comment': 'query-local-address	Source IP address for sending queries',
                            'default_value': '0.0.0.0', },
    'query-local-address6': {
        'comment': 'query-local-address6	DEPRECATED: Use query-local-address for IPv6 as well. Source IPv6 address for sending queries. IF UNSET, IPv6 WILL NOT BE USED FOR OUTGOING QUERIES',
        'default_value': '', },
    'quiet': {'comment': 'quiet	Suppress logging of questions and answers', 'default_value': None, 'mandatory': True, },
    'record-cache-shards': {'comment': 'record-cache-shards	Number of shards in the record cache', 'default_value': 1024},

    'reuseport': {
        'comment': 'reuseport	Enable SO_REUSEPORT allowing multiple recursors processes to listen to 1 address',
        'default_value': False, },
    'rng': {
        'comment': 'rng	Specify random number generator to use. Valid values are auto,sodium,openssl,getrandom,arc4random,urandom.',
        'default_value': 'auto'},
    'root-nx-trust': {
        'comment': 'root-nx-trust	If set, believe that an NXDOMAIN from the root means the TLD does not exist',
        'default_value': True, },
    'security-poll-suffix': {
        'comment': 'security-poll-suffix	Domain name from which to query security update notifications',
        'default_value': 'secpoll.powerdns.com.', },
    'serve-rfc1918': {'comment': 'serve-rfc1918	If we should be authoritative for RFC 1918 private IP space',
                      'default_value': True, },
    'server-down-max-fails': {
        'comment': 'server-down-max-fails	Maximum number of consecutive timeouts (and unreachables) '
                   'to mark a server as down ( 0 => disabled )',
        'default_value': 64, },
    'server-down-throttle-time': {
        'comment': 'server-down-throttle-time	Number of seconds to throttle all queries to a server '
                   'after being marked as down',
        'default_value': 60, },
    'server-id': {'comment': 'server-id	Returned when queried for \'id.server\' TXT or NSID, defaults to hostname, set custom or \'disabled\'',
                  'default_value': '', },
    'setgid': {'comment': 'setgid	If set, change group id to this gid for more security. When running inside systemd, use the User and Group settings in the unit-file!', 'default_value': ''},
    'setuid': {'comment': 'setuid	If set, change user id to this uid for more security. When running inside systemd, use the User and Group settings in the unit-file!', 'default_value': ''},
    'signature-inception-skew': {'comment': 'signature-inception-skew	Allow the signature inception to be off by this number of seconds', 'default_value': 60},

    'single-socket': {'comment': 'single-socket	If set, only use a single socket for outgoing queries',
                      'default_value': 'off', },
    'snmp-agent': {'comment': 'snmp-agent	If set, register as an SNMP agent', 'default_value': False, },
    'snmp-master-socket': {
        'comment': 'snmp-master-socket	If set and snmp-agent is set, the socket to use to register to the SNMP master',
        'default_value': '', },
    'soa-minimum-ttl': {'comment': 'soa-minimum-ttl	Don\'t change', 'default_value': '0', },
    'socket-dir': {'comment': 'socket-dir	Where the controlsocket will live, /var/run/pdns-recursor when unset and not chrooted. Set to the RUNTIME_DIRECTORY environment variable when that variable has a value (e.g. under systemd).',
                   'default_value': '', },
    'socket-group': {'comment': 'socket-group	Group of socket', 'default_value': '', },
    'socket-mode': {'comment': 'socket-mode	Permissions for socket', 'default_value': '', },
    'socket-owner': {'comment': 'socket-owner	Owner of socket', 'default_value': '', },
    'spoof-nearmiss-max': {'comment': 'spoof-nearmiss-max	If non-zero, assume spoofing after this many near misses',
                           'default_value': 20, },
    'stack-size': {'comment': 'stack-size	stack size per mthread', 'default_value': 200000, },
    'statistics-interval': {
        'comment': 'statistics-interval	Number of seconds between printing of recursor statistics, 0 to disable',
        'default_value': 1800, },
    'stats-api-blacklist': {'comment': 'stats-api-blacklist	List of statistics that are disabled when retrieving the complete list of statistics via the API',
                            'default_value': ['cache-bytes', 'packetcache-bytes', 'special-memory-usage',
                                              'ecs-v4-response-bits-1', 'ecs-v4-response-bits-2',
                                              'ecs-v4-response-bits-3', 'ecs-v4-response-bits-4',
                                              'ecs-v4-response-bits-5', 'ecs-v4-response-bits-6',
                                              'ecs-v4-response-bits-7', 'ecs-v4-response-bits-8',
                                              'ecs-v4-response-bits-9', 'ecs-v4-response-bits-10',
                                              'ecs-v4-response-bits-11', 'ecs-v4-response-bits-12',
                                              'ecs-v4-response-bits-13', 'ecs-v4-response-bits-14',
                                              'ecs-v4-response-bits-15', 'ecs-v4-response-bits-16',
                                              'ecs-v4-response-bits-17', 'ecs-v4-response-bits-18',
                                              'ecs-v4-response-bits-19', 'ecs-v4-response-bits-20',
                                              'ecs-v4-response-bits-21', 'ecs-v4-response-bits-22',
                                              'ecs-v4-response-bits-23', 'ecs-v4-response-bits-24',
                                              'ecs-v4-response-bits-25', 'ecs-v4-response-bits-26',
                                              'ecs-v4-response-bits-27', 'ecs-v4-response-bits-28',
                                              'ecs-v4-response-bits-29', 'ecs-v4-response-bits-30',
                                              'ecs-v4-response-bits-31', 'ecs-v4-response-bits-32',
                                              'ecs-v6-response-bits-1', 'ecs-v6-response-bits-2',
                                              'ecs-v6-response-bits-3', 'ecs-v6-response-bits-4',
                                              'ecs-v6-response-bits-5', 'ecs-v6-response-bits-6',
                                              'ecs-v6-response-bits-7', 'ecs-v6-response-bits-8',
                                              'ecs-v6-response-bits-9', 'ecs-v6-response-bits-10',
                                              'ecs-v6-response-bits-11', 'ecs-v6-response-bits-12',
                                              'ecs-v6-response-bits-13', 'ecs-v6-response-bits-14',
                                              'ecs-v6-response-bits-15', 'ecs-v6-response-bits-16',
                                              'ecs-v6-response-bits-17', 'ecs-v6-response-bits-18',
                                              'ecs-v6-response-bits-19', 'ecs-v6-response-bits-20',
                                              'ecs-v6-response-bits-21', 'ecs-v6-response-bits-22',
                                              'ecs-v6-response-bits-23', 'ecs-v6-response-bits-24',
                                              'ecs-v6-response-bits-25', 'ecs-v6-response-bits-26',
                                              'ecs-v6-response-bits-27', 'ecs-v6-response-bits-28',
                                              'ecs-v6-response-bits-29', 'ecs-v6-response-bits-30',
                                              'ecs-v6-response-bits-31', 'ecs-v6-response-bits-32',
                                              'ecs-v6-response-bits-33', 'ecs-v6-response-bits-34',
                                              'ecs-v6-response-bits-35', 'ecs-v6-response-bits-36',
                                              'ecs-v6-response-bits-37', 'ecs-v6-response-bits-38',
                                              'ecs-v6-response-bits-39', 'ecs-v6-response-bits-40',
                                              'ecs-v6-response-bits-41', 'ecs-v6-response-bits-42',
                                              'ecs-v6-response-bits-43', 'ecs-v6-response-bits-44',
                                              'ecs-v6-response-bits-45', 'ecs-v6-response-bits-46',
                                              'ecs-v6-response-bits-47', 'ecs-v6-response-bits-48',
                                              'ecs-v6-response-bits-49', 'ecs-v6-response-bits-50',
                                              'ecs-v6-response-bits-51', 'ecs-v6-response-bits-52',
                                              'ecs-v6-response-bits-53', 'ecs-v6-response-bits-54',
                                              'ecs-v6-response-bits-55', 'ecs-v6-response-bits-56',
                                              'ecs-v6-response-bits-57', 'ecs-v6-response-bits-58',
                                              'ecs-v6-response-bits-59', 'ecs-v6-response-bits-60',
                                              'ecs-v6-response-bits-61', 'ecs-v6-response-bits-62',
                                              'ecs-v6-response-bits-63', 'ecs-v6-response-bits-64',
                                              'ecs-v6-response-bits-65', 'ecs-v6-response-bits-66',
                                              'ecs-v6-response-bits-67', 'ecs-v6-response-bits-68',
                                              'ecs-v6-response-bits-69', 'ecs-v6-response-bits-70',
                                              'ecs-v6-response-bits-71', 'ecs-v6-response-bits-72',
                                              'ecs-v6-response-bits-73', 'ecs-v6-response-bits-74',
                                              'ecs-v6-response-bits-75', 'ecs-v6-response-bits-76',
                                              'ecs-v6-response-bits-77', 'ecs-v6-response-bits-78',
                                              'ecs-v6-response-bits-79', 'ecs-v6-response-bits-80',
                                              'ecs-v6-response-bits-81', 'ecs-v6-response-bits-82',
                                              'ecs-v6-response-bits-83', 'ecs-v6-response-bits-84',
                                              'ecs-v6-response-bits-85', 'ecs-v6-response-bits-86',
                                              'ecs-v6-response-bits-87', 'ecs-v6-response-bits-88',
                                              'ecs-v6-response-bits-89', 'ecs-v6-response-bits-90',
                                              'ecs-v6-response-bits-91', 'ecs-v6-response-bits-92',
                                              'ecs-v6-response-bits-93', 'ecs-v6-response-bits-94',
                                              'ecs-v6-response-bits-95', 'ecs-v6-response-bits-96',
                                              'ecs-v6-response-bits-97', 'ecs-v6-response-bits-98',
                                              'ecs-v6-response-bits-99', 'ecs-v6-response-bits-100',
                                              'ecs-v6-response-bits-101', 'ecs-v6-response-bits-102',
                                              'ecs-v6-response-bits-103', 'ecs-v6-response-bits-104',
                                              'ecs-v6-response-bits-105', 'ecs-v6-response-bits-106',
                                              'ecs-v6-response-bits-107', 'ecs-v6-response-bits-108',
                                              'ecs-v6-response-bits-109', 'ecs-v6-response-bits-110',
                                              'ecs-v6-response-bits-111', 'ecs-v6-response-bits-112',
                                              'ecs-v6-response-bits-113', 'ecs-v6-response-bits-114',
                                              'ecs-v6-response-bits-115', 'ecs-v6-response-bits-116',
                                              'ecs-v6-response-bits-117', 'ecs-v6-response-bits-118',
                                              'ecs-v6-response-bits-119', 'ecs-v6-response-bits-120',
                                              'ecs-v6-response-bits-121', 'ecs-v6-response-bits-122',
                                              'ecs-v6-response-bits-123', 'ecs-v6-response-bits-124',
                                              'ecs-v6-response-bits-125', 'ecs-v6-response-bits-126',
                                              'ecs-v6-response-bits-127', 'ecs-v6-response-bits-128']},
    'stats-carbon-blacklist': {'comment': 'stats-carbon-blacklist	List of statistics that are prevented from being exported via Carbon',
                               'default_value': ['cache-bytes', 'packetcache-bytes', 'special-memory-usage',
                                                 'ecs-v4-response-bits-1', 'ecs-v4-response-bits-2',
                                                 'ecs-v4-response-bits-3', 'ecs-v4-response-bits-4',
                                                 'ecs-v4-response-bits-5', 'ecs-v4-response-bits-6',
                                                 'ecs-v4-response-bits-7', 'ecs-v4-response-bits-8',
                                                 'ecs-v4-response-bits-9', 'ecs-v4-response-bits-10',
                                                 'ecs-v4-response-bits-11', 'ecs-v4-response-bits-12',
                                                 'ecs-v4-response-bits-13', 'ecs-v4-response-bits-14',
                                                 'ecs-v4-response-bits-15', 'ecs-v4-response-bits-16',
                                                 'ecs-v4-response-bits-17', 'ecs-v4-response-bits-18',
                                                 'ecs-v4-response-bits-19', 'ecs-v4-response-bits-20',
                                                 'ecs-v4-response-bits-21', 'ecs-v4-response-bits-22',
                                                 'ecs-v4-response-bits-23', 'ecs-v4-response-bits-24',
                                                 'ecs-v4-response-bits-25', 'ecs-v4-response-bits-26',
                                                 'ecs-v4-response-bits-27', 'ecs-v4-response-bits-28',
                                                 'ecs-v4-response-bits-29', 'ecs-v4-response-bits-30',
                                                 'ecs-v4-response-bits-31', 'ecs-v4-response-bits-32',
                                                 'ecs-v6-response-bits-1', 'ecs-v6-response-bits-2',
                                                 'ecs-v6-response-bits-3', 'ecs-v6-response-bits-4',
                                                 'ecs-v6-response-bits-5', 'ecs-v6-response-bits-6',
                                                 'ecs-v6-response-bits-7', 'ecs-v6-response-bits-8',
                                                 'ecs-v6-response-bits-9', 'ecs-v6-response-bits-10',
                                                 'ecs-v6-response-bits-11', 'ecs-v6-response-bits-12',
                                                 'ecs-v6-response-bits-13', 'ecs-v6-response-bits-14',
                                                 'ecs-v6-response-bits-15', 'ecs-v6-response-bits-16',
                                                 'ecs-v6-response-bits-17', 'ecs-v6-response-bits-18',
                                                 'ecs-v6-response-bits-19', 'ecs-v6-response-bits-20',
                                                 'ecs-v6-response-bits-21', 'ecs-v6-response-bits-22',
                                                 'ecs-v6-response-bits-23', 'ecs-v6-response-bits-24',
                                                 'ecs-v6-response-bits-25', 'ecs-v6-response-bits-26',
                                                 'ecs-v6-response-bits-27', 'ecs-v6-response-bits-28',
                                                 'ecs-v6-response-bits-29', 'ecs-v6-response-bits-30',
                                                 'ecs-v6-response-bits-31', 'ecs-v6-response-bits-32',
                                                 'ecs-v6-response-bits-33', 'ecs-v6-response-bits-34',
                                                 'ecs-v6-response-bits-35', 'ecs-v6-response-bits-36',
                                                 'ecs-v6-response-bits-37', 'ecs-v6-response-bits-38',
                                                 'ecs-v6-response-bits-39', 'ecs-v6-response-bits-40',
                                                 'ecs-v6-response-bits-41', 'ecs-v6-response-bits-42',
                                                 'ecs-v6-response-bits-43', 'ecs-v6-response-bits-44',
                                                 'ecs-v6-response-bits-45', 'ecs-v6-response-bits-46',
                                                 'ecs-v6-response-bits-47', 'ecs-v6-response-bits-48',
                                                 'ecs-v6-response-bits-49', 'ecs-v6-response-bits-50',
                                                 'ecs-v6-response-bits-51', 'ecs-v6-response-bits-52',
                                                 'ecs-v6-response-bits-53', 'ecs-v6-response-bits-54',
                                                 'ecs-v6-response-bits-55', 'ecs-v6-response-bits-56',
                                                 'ecs-v6-response-bits-57', 'ecs-v6-response-bits-58',
                                                 'ecs-v6-response-bits-59', 'ecs-v6-response-bits-60',
                                                 'ecs-v6-response-bits-61', 'ecs-v6-response-bits-62',
                                                 'ecs-v6-response-bits-63', 'ecs-v6-response-bits-64',
                                                 'ecs-v6-response-bits-65', 'ecs-v6-response-bits-66',
                                                 'ecs-v6-response-bits-67', 'ecs-v6-response-bits-68',
                                                 'ecs-v6-response-bits-69', 'ecs-v6-response-bits-70',
                                                 'ecs-v6-response-bits-71', 'ecs-v6-response-bits-72',
                                                 'ecs-v6-response-bits-73', 'ecs-v6-response-bits-74',
                                                 'ecs-v6-response-bits-75', 'ecs-v6-response-bits-76',
                                                 'ecs-v6-response-bits-77', 'ecs-v6-response-bits-78',
                                                 'ecs-v6-response-bits-79', 'ecs-v6-response-bits-80',
                                                 'ecs-v6-response-bits-81', 'ecs-v6-response-bits-82',
                                                 'ecs-v6-response-bits-83', 'ecs-v6-response-bits-84',
                                                 'ecs-v6-response-bits-85', 'ecs-v6-response-bits-86',
                                                 'ecs-v6-response-bits-87', 'ecs-v6-response-bits-88',
                                                 'ecs-v6-response-bits-89', 'ecs-v6-response-bits-90',
                                                 'ecs-v6-response-bits-91', 'ecs-v6-response-bits-92',
                                                 'ecs-v6-response-bits-93', 'ecs-v6-response-bits-94',
                                                 'ecs-v6-response-bits-95', 'ecs-v6-response-bits-96',
                                                 'ecs-v6-response-bits-97', 'ecs-v6-response-bits-98',
                                                 'ecs-v6-response-bits-99', 'ecs-v6-response-bits-100',
                                                 'ecs-v6-response-bits-101', 'ecs-v6-response-bits-102',
                                                 'ecs-v6-response-bits-103', 'ecs-v6-response-bits-104',
                                                 'ecs-v6-response-bits-105', 'ecs-v6-response-bits-106',
                                                 'ecs-v6-response-bits-107', 'ecs-v6-response-bits-108',
                                                 'ecs-v6-response-bits-109', 'ecs-v6-response-bits-110',
                                                 'ecs-v6-response-bits-111', 'ecs-v6-response-bits-112',
                                                 'ecs-v6-response-bits-113', 'ecs-v6-response-bits-114',
                                                 'ecs-v6-response-bits-115', 'ecs-v6-response-bits-116',
                                                 'ecs-v6-response-bits-117', 'ecs-v6-response-bits-118',
                                                 'ecs-v6-response-bits-119', 'ecs-v6-response-bits-120',
                                                 'ecs-v6-response-bits-121', 'ecs-v6-response-bits-122',
                                                 'ecs-v6-response-bits-123', 'ecs-v6-response-bits-124',
                                                 'ecs-v6-response-bits-125', 'ecs-v6-response-bits-126',
                                                 'ecs-v6-response-bits-127', 'ecs-v6-response-bits-128']},
    'stats-rec-control-blacklist': {'comment': 'stats-rec-control-blacklist	List of statistics that are prevented from being exported via rec_control get-all',
                                    'default_value': ['cache-bytes', 'packetcache-bytes', 'special-memory-usage',
                                                      'ecs-v4-response-bits-1', 'ecs-v4-response-bits-2',
                                                      'ecs-v4-response-bits-3', 'ecs-v4-response-bits-4',
                                                      'ecs-v4-response-bits-5', 'ecs-v4-response-bits-6',
                                                      'ecs-v4-response-bits-7', 'ecs-v4-response-bits-8',
                                                      'ecs-v4-response-bits-9', 'ecs-v4-response-bits-10',
                                                      'ecs-v4-response-bits-11', 'ecs-v4-response-bits-12',
                                                      'ecs-v4-response-bits-13', 'ecs-v4-response-bits-14',
                                                      'ecs-v4-response-bits-15', 'ecs-v4-response-bits-16',
                                                      'ecs-v4-response-bits-17', 'ecs-v4-response-bits-18',
                                                      'ecs-v4-response-bits-19', 'ecs-v4-response-bits-20',
                                                      'ecs-v4-response-bits-21', 'ecs-v4-response-bits-22',
                                                      'ecs-v4-response-bits-23', 'ecs-v4-response-bits-24',
                                                      'ecs-v4-response-bits-25', 'ecs-v4-response-bits-26',
                                                      'ecs-v4-response-bits-27', 'ecs-v4-response-bits-28',
                                                      'ecs-v4-response-bits-29', 'ecs-v4-response-bits-30',
                                                      'ecs-v4-response-bits-31', 'ecs-v4-response-bits-32',
                                                      'ecs-v6-response-bits-1', 'ecs-v6-response-bits-2',
                                                      'ecs-v6-response-bits-3', 'ecs-v6-response-bits-4',
                                                      'ecs-v6-response-bits-5', 'ecs-v6-response-bits-6',
                                                      'ecs-v6-response-bits-7', 'ecs-v6-response-bits-8',
                                                      'ecs-v6-response-bits-9', 'ecs-v6-response-bits-10',
                                                      'ecs-v6-response-bits-11', 'ecs-v6-response-bits-12',
                                                      'ecs-v6-response-bits-13', 'ecs-v6-response-bits-14',
                                                      'ecs-v6-response-bits-15', 'ecs-v6-response-bits-16',
                                                      'ecs-v6-response-bits-17', 'ecs-v6-response-bits-18',
                                                      'ecs-v6-response-bits-19', 'ecs-v6-response-bits-20',
                                                      'ecs-v6-response-bits-21', 'ecs-v6-response-bits-22',
                                                      'ecs-v6-response-bits-23', 'ecs-v6-response-bits-24',
                                                      'ecs-v6-response-bits-25', 'ecs-v6-response-bits-26',
                                                      'ecs-v6-response-bits-27', 'ecs-v6-response-bits-28',
                                                      'ecs-v6-response-bits-29', 'ecs-v6-response-bits-30',
                                                      'ecs-v6-response-bits-31', 'ecs-v6-response-bits-32',
                                                      'ecs-v6-response-bits-33', 'ecs-v6-response-bits-34',
                                                      'ecs-v6-response-bits-35', 'ecs-v6-response-bits-36',
                                                      'ecs-v6-response-bits-37', 'ecs-v6-response-bits-38',
                                                      'ecs-v6-response-bits-39', 'ecs-v6-response-bits-40',
                                                      'ecs-v6-response-bits-41', 'ecs-v6-response-bits-42',
                                                      'ecs-v6-response-bits-43', 'ecs-v6-response-bits-44',
                                                      'ecs-v6-response-bits-45', 'ecs-v6-response-bits-46',
                                                      'ecs-v6-response-bits-47', 'ecs-v6-response-bits-48',
                                                      'ecs-v6-response-bits-49', 'ecs-v6-response-bits-50',
                                                      'ecs-v6-response-bits-51', 'ecs-v6-response-bits-52',
                                                      'ecs-v6-response-bits-53', 'ecs-v6-response-bits-54',
                                                      'ecs-v6-response-bits-55', 'ecs-v6-response-bits-56',
                                                      'ecs-v6-response-bits-57', 'ecs-v6-response-bits-58',
                                                      'ecs-v6-response-bits-59', 'ecs-v6-response-bits-60',
                                                      'ecs-v6-response-bits-61', 'ecs-v6-response-bits-62',
                                                      'ecs-v6-response-bits-63', 'ecs-v6-response-bits-64',
                                                      'ecs-v6-response-bits-65', 'ecs-v6-response-bits-66',
                                                      'ecs-v6-response-bits-67', 'ecs-v6-response-bits-68',
                                                      'ecs-v6-response-bits-69', 'ecs-v6-response-bits-70',
                                                      'ecs-v6-response-bits-71', 'ecs-v6-response-bits-72',
                                                      'ecs-v6-response-bits-73', 'ecs-v6-response-bits-74',
                                                      'ecs-v6-response-bits-75', 'ecs-v6-response-bits-76',
                                                      'ecs-v6-response-bits-77', 'ecs-v6-response-bits-78',
                                                      'ecs-v6-response-bits-79', 'ecs-v6-response-bits-80',
                                                      'ecs-v6-response-bits-81', 'ecs-v6-response-bits-82',
                                                      'ecs-v6-response-bits-83', 'ecs-v6-response-bits-84',
                                                      'ecs-v6-response-bits-85', 'ecs-v6-response-bits-86',
                                                      'ecs-v6-response-bits-87', 'ecs-v6-response-bits-88',
                                                      'ecs-v6-response-bits-89', 'ecs-v6-response-bits-90',
                                                      'ecs-v6-response-bits-91', 'ecs-v6-response-bits-92',
                                                      'ecs-v6-response-bits-93', 'ecs-v6-response-bits-94',
                                                      'ecs-v6-response-bits-95', 'ecs-v6-response-bits-96',
                                                      'ecs-v6-response-bits-97', 'ecs-v6-response-bits-98',
                                                      'ecs-v6-response-bits-99', 'ecs-v6-response-bits-100',
                                                      'ecs-v6-response-bits-101', 'ecs-v6-response-bits-102',
                                                      'ecs-v6-response-bits-103', 'ecs-v6-response-bits-104',
                                                      'ecs-v6-response-bits-105', 'ecs-v6-response-bits-106',
                                                      'ecs-v6-response-bits-107', 'ecs-v6-response-bits-108',
                                                      'ecs-v6-response-bits-109', 'ecs-v6-response-bits-110',
                                                      'ecs-v6-response-bits-111', 'ecs-v6-response-bits-112',
                                                      'ecs-v6-response-bits-113', 'ecs-v6-response-bits-114',
                                                      'ecs-v6-response-bits-115', 'ecs-v6-response-bits-116',
                                                      'ecs-v6-response-bits-117', 'ecs-v6-response-bits-118',
                                                      'ecs-v6-response-bits-119', 'ecs-v6-response-bits-120',
                                                      'ecs-v6-response-bits-121', 'ecs-v6-response-bits-122',
                                                      'ecs-v6-response-bits-123', 'ecs-v6-response-bits-124',
                                                      'ecs-v6-response-bits-125', 'ecs-v6-response-bits-126',
                                                      'ecs-v6-response-bits-127', 'ecs-v6-response-bits-128']},


    'stats-ringbuffer-entries': {
        'comment': 'stats-ringbuffer-entries	maximum number of packets to store statistics for',
        'default_value': 10000, },
    'stats-snmp-blacklist': {'comment': 'stats-snmp-blacklist	List of statistics that are prevented from being exported via SNMP',
                             'default_value': ['cache-bytes', 'packetcache-bytes', 'special-memory-usage',
                                               'ecs-v4-response-bits-1', 'ecs-v4-response-bits-2',
                                               'ecs-v4-response-bits-3', 'ecs-v4-response-bits-4',
                                               'ecs-v4-response-bits-5', 'ecs-v4-response-bits-6',
                                               'ecs-v4-response-bits-7', 'ecs-v4-response-bits-8',
                                               'ecs-v4-response-bits-9', 'ecs-v4-response-bits-10',
                                               'ecs-v4-response-bits-11', 'ecs-v4-response-bits-12',
                                               'ecs-v4-response-bits-13', 'ecs-v4-response-bits-14',
                                               'ecs-v4-response-bits-15', 'ecs-v4-response-bits-16',
                                               'ecs-v4-response-bits-17', 'ecs-v4-response-bits-18',
                                               'ecs-v4-response-bits-19', 'ecs-v4-response-bits-20',
                                               'ecs-v4-response-bits-21', 'ecs-v4-response-bits-22',
                                               'ecs-v4-response-bits-23', 'ecs-v4-response-bits-24',
                                               'ecs-v4-response-bits-25', 'ecs-v4-response-bits-26',
                                               'ecs-v4-response-bits-27', 'ecs-v4-response-bits-28',
                                               'ecs-v4-response-bits-29', 'ecs-v4-response-bits-30',
                                               'ecs-v4-response-bits-31', 'ecs-v4-response-bits-32',
                                               'ecs-v6-response-bits-1', 'ecs-v6-response-bits-2',
                                               'ecs-v6-response-bits-3', 'ecs-v6-response-bits-4',
                                               'ecs-v6-response-bits-5', 'ecs-v6-response-bits-6',
                                               'ecs-v6-response-bits-7', 'ecs-v6-response-bits-8',
                                               'ecs-v6-response-bits-9', 'ecs-v6-response-bits-10',
                                               'ecs-v6-response-bits-11', 'ecs-v6-response-bits-12',
                                               'ecs-v6-response-bits-13', 'ecs-v6-response-bits-14',
                                               'ecs-v6-response-bits-15', 'ecs-v6-response-bits-16',
                                               'ecs-v6-response-bits-17', 'ecs-v6-response-bits-18',
                                               'ecs-v6-response-bits-19', 'ecs-v6-response-bits-20',
                                               'ecs-v6-response-bits-21', 'ecs-v6-response-bits-22',
                                               'ecs-v6-response-bits-23', 'ecs-v6-response-bits-24',
                                               'ecs-v6-response-bits-25', 'ecs-v6-response-bits-26',
                                               'ecs-v6-response-bits-27', 'ecs-v6-response-bits-28',
                                               'ecs-v6-response-bits-29', 'ecs-v6-response-bits-30',
                                               'ecs-v6-response-bits-31', 'ecs-v6-response-bits-32',
                                               'ecs-v6-response-bits-33', 'ecs-v6-response-bits-34',
                                               'ecs-v6-response-bits-35', 'ecs-v6-response-bits-36',
                                               'ecs-v6-response-bits-37', 'ecs-v6-response-bits-38',
                                               'ecs-v6-response-bits-39', 'ecs-v6-response-bits-40',
                                               'ecs-v6-response-bits-41', 'ecs-v6-response-bits-42',
                                               'ecs-v6-response-bits-43', 'ecs-v6-response-bits-44',
                                               'ecs-v6-response-bits-45', 'ecs-v6-response-bits-46',
                                               'ecs-v6-response-bits-47', 'ecs-v6-response-bits-48',
                                               'ecs-v6-response-bits-49', 'ecs-v6-response-bits-50',
                                               'ecs-v6-response-bits-51', 'ecs-v6-response-bits-52',
                                               'ecs-v6-response-bits-53', 'ecs-v6-response-bits-54',
                                               'ecs-v6-response-bits-55', 'ecs-v6-response-bits-56',
                                               'ecs-v6-response-bits-57', 'ecs-v6-response-bits-58',
                                               'ecs-v6-response-bits-59', 'ecs-v6-response-bits-60',
                                               'ecs-v6-response-bits-61', 'ecs-v6-response-bits-62',
                                               'ecs-v6-response-bits-63', 'ecs-v6-response-bits-64',
                                               'ecs-v6-response-bits-65', 'ecs-v6-response-bits-66',
                                               'ecs-v6-response-bits-67', 'ecs-v6-response-bits-68',
                                               'ecs-v6-response-bits-69', 'ecs-v6-response-bits-70',
                                               'ecs-v6-response-bits-71', 'ecs-v6-response-bits-72',
                                               'ecs-v6-response-bits-73', 'ecs-v6-response-bits-74',
                                               'ecs-v6-response-bits-75', 'ecs-v6-response-bits-76',
                                               'ecs-v6-response-bits-77', 'ecs-v6-response-bits-78',
                                               'ecs-v6-response-bits-79', 'ecs-v6-response-bits-80',
                                               'ecs-v6-response-bits-81', 'ecs-v6-response-bits-82',
                                               'ecs-v6-response-bits-83', 'ecs-v6-response-bits-84',
                                               'ecs-v6-response-bits-85', 'ecs-v6-response-bits-86',
                                               'ecs-v6-response-bits-87', 'ecs-v6-response-bits-88',
                                               'ecs-v6-response-bits-89', 'ecs-v6-response-bits-90',
                                               'ecs-v6-response-bits-91', 'ecs-v6-response-bits-92',
                                               'ecs-v6-response-bits-93', 'ecs-v6-response-bits-94',
                                               'ecs-v6-response-bits-95', 'ecs-v6-response-bits-96',
                                               'ecs-v6-response-bits-97', 'ecs-v6-response-bits-98',
                                               'ecs-v6-response-bits-99', 'ecs-v6-response-bits-100',
                                               'ecs-v6-response-bits-101', 'ecs-v6-response-bits-102',
                                               'ecs-v6-response-bits-103', 'ecs-v6-response-bits-104',
                                               'ecs-v6-response-bits-105', 'ecs-v6-response-bits-106',
                                               'ecs-v6-response-bits-107', 'ecs-v6-response-bits-108',
                                               'ecs-v6-response-bits-109', 'ecs-v6-response-bits-110',
                                               'ecs-v6-response-bits-111', 'ecs-v6-response-bits-112',
                                               'ecs-v6-response-bits-113', 'ecs-v6-response-bits-114',
                                               'ecs-v6-response-bits-115', 'ecs-v6-response-bits-116',
                                               'ecs-v6-response-bits-117', 'ecs-v6-response-bits-118',
                                               'ecs-v6-response-bits-119', 'ecs-v6-response-bits-120',
                                               'ecs-v6-response-bits-121', 'ecs-v6-response-bits-122',
                                               'ecs-v6-response-bits-123', 'ecs-v6-response-bits-124',
                                               'ecs-v6-response-bits-125', 'ecs-v6-response-bits-126',
                                               'ecs-v6-response-bits-127', 'ecs-v6-response-bits-128']},

    'tcp-fast-open': {
        'comment': 'tcp-fast-open	Enable TCP Fast Open support on the listening sockets, '
                   'using the supplied numerical value as the queue size',
        'default_value': '0', },
    'threads': {'comment': 'threads	Launch this number of threads', 'default_value': 2, },
    'trace': {'comment': 'trace	if we should output heaps of logging. set to \'fail\' to only log failing domains',
              'default_value': 'off', },
    'udp-source-port-avoid': {'comment': 'udp-source-port-avoid	List of comma separated UDP port number to avoid', 'default_value': 11211},
    'udp-source-port-max': {'comment': 'udp-source-port-max	Maximum UDP port to bind on', 'default_value': 65535},
    'udp-source-port-min': {'comment': 'udp-source-port-min	Minimum UDP port to bind on', 'default_value': 1024},

    'udp-truncation-threshold': {'comment': 'udp-truncation-threshold	Maximum UDP response size before we truncate',
                                 'default_value': 1232, },
    'use-incoming-edns-subnet': {
        'comment': 'use-incoming-edns-subnet	Pass along received EDNS Client Subnet information',
        'default_value': False, },
    'version-string': {'comment': 'version-string	string reported on version.pdns or version.bind',
                       'default_value': '', },
    'webserver': {'comment': 'webserver	Start a webserver (for REST API)', 'default_value': False, },
    'webserver-address': {'comment': 'webserver-address	IP Address of webserver to listen on',
                          'default_value': '127.0.0.1', },
    'webserver-allow-from': {'comment': 'webserver-allow-from	Webserver access is only allowed from these subnets',
                             'default_value': '127.0.0.1,::1', },
    'webserver-loglevel': {'comment': 'webserver-loglevel	Amount of logging in the webserver (none, normal, detailed)', 'default_value': 'normal'},

    'webserver-password': {'comment': 'webserver-password	Password required for accessing the webserver',
                           'default_value': '', },
    'webserver-port': {'comment': 'webserver-port	Port of webserver to listen on', 'default_value': 8082, },
    'write-pid': {'comment': 'write-pid	Write a PID file', 'default_value': True, },
    'xpf-allow-from': {'comment': 'xpf-allow-from	XPF information is only processed from these subnets', 'default_value': ''},
    'xpf-rr-code': {'comment': 'xpf-rr-code	XPF option code to use', 'default_value': 0},
}

# set pdns_config to pdns_default_config
pdns_configs = {x: y.get('default_value', None) for (x, y) in pdns_default_config.items()}.copy()

# set this to known values
pdns_configs.update({
    'include-dir': '/etc/powerdns/pdns.d',
    'launch': '',
    'security-poll-suffix': '',
    # 'setgid': 'pdns',
    # 'setuid': 'pdns',
})

recursor_config = node.metadata.get('powerdns', {}).get('recursor', {})

if recursor_config.get('enabled', False):
    svc_systemd['pdns-recursor.service'] = {'needs': ['pkg_apt:pdns-recursor', ], }

    pdns_configs.update({
        'local-address': '127.0.0.1',
        'local-port': 5300,
    })

    pdns_recursor_configs = {x: y.get('default_value', None) for (x, y) in pdns_recursor_default_config.items()}.copy()

    pdns_recursor_configs.update({
        'config-dir': '/etc/powerdns',
        'hint-file': '/usr/share/dns/root.hints',
        'include-dir': '/etc/powerdns/recursor.d',
        'local-address': ['0.0.0.0', '[::]'],
        'lua-config-file': '/etc/powerdns/recursor.lua',
        'public-suffix-list-file': '/usr/share/publicsuffix/public_suffix_list.dat',
        'quiet': True,
        'security-poll-suffix': '',
        # 'setgid': 'pdns',
        # 'setuid': 'pdns',
        'forward-zones-file': '/etc/powerdns/forward-zones.conf',
    })

    pdns_recursor_configs.update(node.metadata.get('powerdns', {}).get('recursor', {}).get('config', {}))

    files['/etc/powerdns/recursor.conf'] = {
        'content': '\n'.join(generate_content(
            dns_config=pdns_recursor_configs,
            default_config=pdns_recursor_default_config)) + '\n',
        'mode': "0600",
        'owner': 'pdns',
        'group': 'pdns',
        'triggers': [
            "svc_systemd:pdns-recursor.service:restart"
        ],
    }

    forward_zones = [f'{x}=127.0.0.1:5300' for x in sorted(node.metadata.get('powerdns', {})
                     .get('backends', {}).get('bind', {}).get('zones', {}).keys())]

    files['/etc/powerdns/forward-zones.conf'] = {
        'content': '\n'.join(forward_zones) + '\n',
        'mode': "0644",
        'owner': 'pdns',
        'group': 'pdns',
        'triggers': [
            "svc_systemd:pdns-recursor.service:restart"
        ],

    }


pdns_configs.update(node.metadata.get('powerdns', {}).get('config', {}))

files['/etc/powerdns/pdns.conf'] = {
    'content': '\n'.join(generate_content(dns_config=pdns_configs, default_config=pdns_default_config)) + '\n',
    'mode': "0640",
    'owner': 'pdns',
    'group': 'pdns',
    'triggers': [
        "svc_systemd:pdns:restart"
    ],
}

dnssec_db = node.metadata\
    .get('powerdns', {}).get('backends', {})\
    .get('bind', {})\
    .get('config', {})\
    .get('bind-dnssec-db', '/var/lib/powerdns/bind-dnssec-db.sqlite3')


actions = {
    "create_dnssec_db": {
        'command': "pdnsutil create-bind-db {dnssec_db}".format(dnssec_db=dnssec_db),
        'unless': "test -f {dnssec_db}".format(dnssec_db=dnssec_db),
        'cascade_skip': False,
        'needs': ["pkg_apt:pdns-server"],
        'triggers': ['svc_systemd:pdns:restart'],
    },
}

directories = {}
zonefiles = {}
zones_dnssec = {}

for backend, config in node.metadata.get('powerdns', {}).get('backends', {}).items():
    apt = config.get('apt', 'pdns-backend-{}'.format(backend))
    pkg_apt[apt] = {
       'installed': True,
       'needs': ['pkg_apt:pdns-server'],
       'needed_by': ['svc_systemd:pdns']
    }

    backend_config = {}
    backend_default_config = {}
    backend_add_config = {}
    backend_config_filename = 'pdns.local.{}.conf'.format(backend)

    if backend == 'gmysql':
        backend_default_config = {
            'launch+': {'default_value': ''},  # no comment, so we do not print the comment
            'gmysql-host': {'comment': '', 'default_value': 'localhost'},
            'gmysql-port': {'comment': '', 'default_value': '3306'},
            'gmysql-dbname': {'comment': '', 'default_value': ''},
            'gmysql-user': {'comment': '', 'default_value': ''},
            'gmysql-password': {'comment': '', 'default_value': ''},
            'gmysql-dnssec': {'comment': '', 'default_value': 'no'},
        }

        backend_add_config = {
            'launch+': 'gmysql',
        }
    elif backend == 'bind':
        backend_config_filename = 'bind.conf'
        backend_default_config = {
            'launch+': {'default_value': ''},  # no comment, so we do not print the comment
            'bind-check-interval': {'comment': 'bind-check-interval	Interval for zonefile changes', 'default_value': 0},
            'bind-config': {'comment': 'bind-config	Location of named.conf', 'default_value': ''},
            'bind-dnssec-db': {'comment': 'bind-dnssec-db	'
                                          'Filename to store & access our DNSSEC metadatabase, empty for none',
                               'default_value': ''},
            'bind-dnssec-db-journal-mode': {'comment': 'bind-dnssec-db-journal-mode	SQLite3 journal mode',
                                            'default_value': 'WAL'},
            'bind-hybrid': {'comment': 'bind-hybrid	Store DNSSEC metadata in other backend', 'default_value': False},
            'bind-ignore-broken-records': {'comment': 'bind-ignore-broken-records	'
                                                      'Ignore records that are out-of-bound for the zone.',
                                           'default_value': False},
            'bind-supermaster-config': {'comment': 'bind-supermaster-config	Location of (part of) named.conf where '
                                                   'pdns can write zone-statements to',
                                        'default_value': ''},
            'bind-supermaster-destdir': {'comment': 'bind-supermaster-destdir	Destination directory for newly '
                                                    'added slave zones', 'default_value': '/etc/powerdns'},
            'bind-supermasters': {'comment': 'bind-supermasters	List of IP-addresses of supermasters',
                                  'default_value': ''},
        }

        backend_add_config = {
            'launch+': 'bind',
            'bind-supermaster-config': '/var/lib/powerdns/supermaster.conf',
            'bind-supermaster-destdir': '/var/lib/powerdns/zones.slave.d',
        }

        zonefile_directory = config.get('zonefile_directory', '/var/lib/powerdns/zones')

        directories[zonefile_directory] = {
            'owner': 'root',
            'group': 'pdns',
            'mode': "0750",
            'needs': ['pkg_apt:{}'.format(apt)],
        }

        named_config = [
            '# Debian default: supermaster created zones are written here:',
            'include "/var/lib/powerdns/supermaster.conf";',
        ]

        # load zonefiles
        for zone, zone_config in config.get('zones', {}).items():
            named_config.append('zone "{}" IN {{'.format(zone))
            named_config.append('    type {};'.format(zone_config.get('type', 'master')))
            named_config.append('    file "{}/{}.zone";'.format(zonefile_directory, zone))
            named_config.append('};')

            dnssec_config = zone_config.get('dnssec', None)

            if dnssec_config:
                keys = {}
                for key in dnssec_config.get('keys', []):
                    keys[key.get('public_key', {}).get('key', '')] = {
                        'private_key': repo.vault.decrypt_file('dnssec/{}'.format(
                            key.get('private_key_file', '{}.key'.format(zone)))).value,  # if not set, set to <zone>.key
                        'public_key': key.get('public_key', {}),
                        'active': key.get('active', False),
                    }

                if dnssec_config.get('disabled', False):
                    zones_dnssec[zone] = {
                        'disabled': True,
                    }
                else:
                    zones_dnssec[zone] = {
                        'keys': keys,
                        'nsec3': dnssec_config.get('nsec3', False),
                    }

            # create ns records we add a . to the end of every domain, since we assume they are absolute
            ns_records = []
            for ns in zone_config.get('name_servers', []):
                ns_records += [{'ttl': 86400, 'type': 'NS', 'value': add_dot(ns)}, ]

            actions['notify_zone_{}'.format(zone)] = {
                'command': "pdns_control notify {zone}".format(zone=zone),
                'triggered': True,
            }

            zonefiles[zone] = {
                'soa': {
                    'nameserver': zone_config.get('name_servers', [''])[0],
                    'postmaster': zone_config.get('soa', {}).get('hostmaster', 'hostmaster@ultrachaos.de'),
                    'refresh': zone_config.get('soa', {}).get('refresh', 14400),
                    'retry': zone_config.get('soa', {}).get('retry', 7200),
                    'expire': zone_config.get('soa', {}).get('expire', 604800),
                    'minimum': zone_config.get('soa', {}).get('minimum', 14400),
                },
                'records': {
                    '': ns_records,
                },
                'default_ttl': zone_config.get('default_ttl', 300),
                'zonefile_directory': zonefile_directory,
                'triggers': ['svc_systemd:pdns:restart', 'action:notify_zone_{}'.format(zone)],
                'needs': ['pkg_apt:pdns-server', 'directory:{}'.format(zonefile_directory)],
            }

            zone_type = zone_config.get('zone_type', "static")

            if zone_type == 'dyndns':
                zonefiles[zone]['dynamic'] = True
            elif zone_type == 'group':
                if 'group' not in zone_config:
                    raise BundleError("zonetype is group, but no group defined")

                for gnode in sorted(repo.nodes_in_group(zone_config['group'])):
                    for interface, interface_config in zone_config.get('interfaces', {}).items():
                        ip = gnode.metadata.get('interfaces', {})\
                            .get(interface, {})\
                            .get('ip_addresses', [None, ])[0]

                        # Remove Zone in hostname
                        gnode_name = re.sub("[.]{zone}$".format(zone=zone.replace('.', '[.]')), '', gnode.hostname)

                        if ip:
                            add_to_list_or_create(
                                zonefiles[zone]['records'],
                                '{net}.{name}'.format(net=interface, name=gnode_name),
                                {'type': 'A', 'value': ip}
                            )

                            if interface_config.get('cname', False):
                                add_to_list_or_create(
                                    zonefiles[zone]['records'],
                                    '{}'.format(gnode_name),
                                    {
                                        'type': 'CNAME', 'value': '{net}.{name}'.format(
                                            net=interface,
                                            name=gnode_name
                                        )
                                    }
                                )

                    for name, record in sorted(gnode.metadata.get('powerdns', {}).get('extra_srv_records', {}).items()):
                        add_to_list_or_create(
                            zonefiles[zone]['records'],
                            name,
                            {'type': 'SRV', 'value': (
                                record.get('priority', 10),
                                record.get('weight', 10),
                                record.get('port'),
                                record.get('server')
                            )}
                        )

            extra_records = zone_config.get('records', {})
            for name, items in sorted(extra_records.items()):
                for item in items:
                    add_to_list_or_create(
                        zonefiles[zone]['records'],
                        name,
                        {'type': item.get('type', 'A'), 'value': item.get('value', '')},
                    )

        files['/etc/powerdns/named.conf'] = {
            'content': '\n'.join(named_config) + '\n',
            'mode': "0640",
            'owner': 'root',
            'group': 'pdns',
            'triggers': [
                "svc_systemd:pdns:restart"
            ],
        }

    # set backend_config to backend_default_config
    backend_config = {x: y.get('default_value', None) for (x, y) in backend_default_config.items()}.copy()

    # set this to known values
    backend_config.update(backend_add_config)

    # overwrite config with configured values
    backend_config.update(config.get('config', {}))

    if config.get('enabled', False):
        files['/etc/powerdns/pdns.d/{}'.format(backend_config_filename)] = {
            'content': '\n'.join(generate_content(
                dns_config=backend_config,
                default_config=backend_default_config)) + '\n',
            'mode': "0640",
            'owner': 'pdns',
            'group': 'pdns',
            'triggers': [
                "svc_systemd:pdns:restart"
            ],
        }
    else:
        files['/etc/powerdns/pdns.d/{}'.format(backend_config_filename)] = {
            'delete': True,
            'triggers': [
                "svc_systemd:pdns:restart"
            ],
        }
